In [9]:
import numpy as np
from scipy import misc

In [2]:
a = np.array([[1,2,3],
      [4,5,6],
      [7,8,9]])

In [3]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
(a==(4,5,6))

array([[False, False, False],
       [ True,  True,  True],
       [False, False, False]])

In [7]:
(a==(4,5,6)).all(axis=1)

array([False,  True, False])

In [8]:
np.where((a==(4,5,6)).all(axis=1))

(array([1], dtype=int64),)

In [30]:
img_4 = misc.imread("1_2.png", flatten="True")
img_4_resized = misc.imresize(img_4, (50,99), interp="bilinear")
kathi = np.invert(img_4_resized)

C:\Users\S795641\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  """Entry point for launching an IPython kernel.
C:\Users\S795641\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.
  


In [31]:
kathi.shape

(50, 99)

In [32]:
kathi_zero = np.zeros((50,1), dtype=int)

In [33]:
kathi_r = np.where((kathi==kathi_zero).all(axis=0))

In [34]:
kathi_np = kathi_r[0]

In [35]:
kathi_np.shape

(68,)

In [37]:
r = kathi_np.shape[0]/2

In [40]:
kathi_np[int(r)]

39

In [42]:
kathi_final = np.split(kathi, 2, axis=0)

In [46]:
len(kathi_final)

2